# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbcli < Formula
  desc "qbcli - Command-line interface for QuickBooks Online"
  homepage "https://github.com/xtoolsio/xTools"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v0.3.0/qbcli_0.3.0_darwin_amd64.tar.gz"
      sha256 "d683345669862c343a1e9b58b7a51908a59b42126b103ba7d7592872c9d855f6"

      def install
        bin.install "qbcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v0.3.0/qbcli_0.3.0_darwin_arm64.tar.gz"
      sha256 "b0ddeeacdcdf912121fe3abc810641edda1cee6e77c0f7760837efdafc72eb6d"

      def install
        bin.install "qbcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v0.3.0/qbcli_0.3.0_linux_amd64.tar.gz"
      sha256 "8659521d112e9c9773d789e7735683e74db46bf2af0fac6e678033219d7958b2"
      def install
        bin.install "qbcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v0.3.0/qbcli_0.3.0_linux_arm64.tar.gz"
      sha256 "7f5edee91189e13fc905451df077ea04b3cb8171f584bfe12f121243e2541d51"
      def install
        bin.install "qbcli"
      end
    end
  end
end
