# This file was generated by GoReleaser. DO NOT EDIT.
cask "qbcli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/qbcli"]
    end
  end

  version "0.5.4"

  on_macos do
    on_arm do
      sha256 "5cca6e481773cd7584a4251df234af62b7f2021029a74efa46eaaaf778cb4b43"
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b4d7231fe1898d0a2a861b05518d3bfea4943aa66848b6b20b8e1acdc95d60a"
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "de922769e7cff9f8283dad9f7781cb78b9e7c66fb3b9581971f7f7b8bca4f572"
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8bf242eab91a839dde33682c6fdbc3c405dd86ec62066a29a629936cea61c72a"
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qbcli"
  desc "Command-line interface for QuickBooks Online"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qbcli"

  # No zap stanza required
end
