# This file was generated by GoReleaser. DO NOT EDIT.
cask "qbcli" do
  name "qbcli"
  desc "qbcli - Command-line interface for QuickBooks Online"
  homepage "https://github.com/xtoolsio/xTools"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qbcli"

  on_macos do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_darwin_amd64.tar.gz"
      sha256 "516973215321c4e7efac94ea4cad6be179fc2f9a13a661d854e77d66ee0ba6c9"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_darwin_arm64.tar.gz"
      sha256 "f310161eb0f316f0e96be9c2695950c0d405ed6bb5800e607fa3af4306583eca"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_linux_amd64.tar.gz"
      sha256 "586b74a20567731fc978bfc5b157557edd822fe7d4ec2d04784be57405f4792d"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/qbcli/v#{version}/qbcli_#{version}_linux_arm64.tar.gz"
      sha256 "9817d36226274e90f636643ebcf2cf30e2fdda6710a7bbd9c8e077bfbe15fbe2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qbcli"]
    end
  end

  # No zap stanza required
end
