# This file was generated by GoReleaser. DO NOT EDIT.
cask "xapollo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "376a58b13f8650945d569208397234820e4f8ba54195a2371116e117eec1d8d3"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xapollo/v#{version}/xapollo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1414b6d98e2868e98dcc309548088f939c2b2d3749feb32340a27f87fcb0c69"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xapollo/v#{version}/xapollo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30646c00ec0c3acdcc3f1e5a886309d71d29757d2142d376b05f59b11986548d"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xapollo/v#{version}/xapollo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "90b480e591f70cfa9a23f6a221afdd83d41e60f3078c4489a9c9ce65b6269473"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xapollo/v#{version}/xapollo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xapollo"
  desc "xapollo - CLI client for the Apollo.io API"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xapollo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xapollo"]
    end
  end

  # No zap stanza required

end
