# This file was generated by GoReleaser. DO NOT EDIT.
cask "xbid" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "01ced7c85b163d37ac4b23a2d136a13ff147b5d987416ce3258b78322bea990b"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2f44dc499e7c64c3a3e7cdc37d7140ee8c9adb013f642634e7e8b0378b5214e"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46eda30a34446490d1e9dff2aa5c50797eb53f313b78542d69e40447f86761fa"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c478fea5589a728b1d9b01ff36646aad326e816ba4cf7bec5dfc6be201c8df5"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xbid"
  desc "xbid - BC Bid procurement-intelligence feed for xCloud sales & marketing"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xbid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xbid"]
    end
  end

  # No zap stanza required

end
