# This file was generated by GoReleaser. DO NOT EDIT.
cask "xbid" do
  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "fe64e3e50cf890383b66a67fab0d8daa3766f246ffbe1d51741f4827fbbbf48c"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "48b32d4f83438853560eafa4f85bb727c7ee1a896d188f69d8f8605d70691ffc"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "116be8b8b45158466ffedebb62d745485096e49d521fe857b224afe6517e9a2d"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "955b4c31d0b939bf90e78ef7a28265220d5ae7a833bb6345520da4942a70629d"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xbid"
  desc "xbid - BC Bid procurement-intelligence feed for xCloud sales & marketing"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xbid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xbid"]
    end
  end

  # No zap stanza required

end
