# This file was generated by GoReleaser. DO NOT EDIT.
cask "xbid" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "a73e5e2a747a6f5b256a8995c8bec438c9113f52d5a0a64e54030c89af722698"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e336915bc77aedf3058feffa790505f3595b7edad72aa1f59af74eae6c4ea1d1"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "61296cca665b9d5ad150e2f08013a18ce61e1fbcca7cd28b011de69fa904cfed"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13fa817a62271542aa1a24b26b1f286de6efc553aa1d24c6b6c7f9bd9d873333"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xbid/v#{version}/xbid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xbid"
  desc "xbid - BC Bid procurement-intelligence feed for xCloud sales & marketing"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xbid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xbid"]
    end
  end

  # No zap stanza required

end
