# This file was generated by GoReleaser. DO NOT EDIT.
cask "xcv" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "aa6a93819c541a401a090d86d1618559b82c393d43ccd16c2dc609ce013ce9a6"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3ec235fbc7a5680229f216d5fe33cfdd36d0f99a829c0c3192f492debe145bf"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0634b3c0ad93e5b7d10b2f3e39f2e6eda40afd0545d6b0447601791ccdc4a439"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12ceaee0a1f024622b7f1e40ee12f005f9fbefb6172d20bef40025897e6e8523"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xcv"
  desc "xcv - AI-facing CV engine: lint a structured CV and render a polished PDF"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "typst",
    ]

  binary "xcv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xcv"]
    end
  end

  # No zap stanza required

end
