# This file was generated by GoReleaser. DO NOT EDIT.
cask "xcv" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "81cba522f6051ab6d0d7cccd5615d589766ed75278452e0879e3319549c98512"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fce74bf0303f5e92a1d972b0bd4420460fa84b3b8b4d2cb22c927b8f55f51db7"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2392977d2ae0edf63ccdf4885998c735827e6f686b263be156bb4825c5463b51"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd73524638d34f0d66fc82b2b197fee12448b0e31aa4272b7ce7b80b9df97519"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xcv"
  desc "xcv - AI-facing CV engine: lint a structured CV and render a polished PDF"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "typst",
    ]

  binary "xcv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xcv"]
    end
  end

  # No zap stanza required

end
