# This file was generated by GoReleaser. DO NOT EDIT.
cask "xcv" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "868227b550ed81709c5d50f22b5bf882c5522c69c9f7f49f7b30b44507798fb1"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "449280134c16040324a7f1c96d6d5eaa46eb3c89bb4ef0f8f1557f9f52950112"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f967001c49b1f1e28a2a8bdec4e8eb03ace5c71e523b8c3002d45a46f3b60b4"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8614603b748257810a3a58298ddce4385fb5f0b5a971dc90ddb7835d3a2c985f"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xcv/v#{version}/xcv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xcv"
  desc "xcv - AI-facing CV engine: lint a structured CV and render a polished PDF"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "typst",
    ]

  binary "xcv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xcv"]
    end
  end

  # No zap stanza required

end
