# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmedia-server" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_darwin_amd64.tar.gz"
      sha256 "f195304bf3d357c12619e6daa64ffab84a7eb0f54fde5213df8a55ed2f334822"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_darwin_arm64.tar.gz"
      sha256 "5e63db3656a9dfa90abfdb635a3b0c7733b0e283939e82ee94a20004af52599e"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_linux_amd64.tar.gz"
      sha256 "8cceb9d54d5b00cc29b0b3b07cd2c9c50ae74c2653c36e37e5159f2a301e996a"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_linux_arm64.tar.gz"
      sha256 "e423c4e0e2f4d7297b038a8ac3bddebf91f08890585fc8b9b106c14ea4ee1f1e"
    end
  end

  name "xmedia-server"
  desc "xmedia-server - Media stack API server for xmedia CLI"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmedia-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmedia-server"]
    end
  end

  # No zap stanza required

end
