# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmedia" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_darwin_amd64.tar.gz"
      sha256 "0303d60efc1ad523b492be585d169f6be0d797eccb37a7f333a2a1e25dceb69f"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_darwin_arm64.tar.gz"
      sha256 "cb47a29248b092843726d8f1dedcda677bfaf72d9ec711e10ab0c6f50098e884"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_linux_amd64.tar.gz"
      sha256 "a24a9921d2fcbe9c94676888a8ea1e67cf92f6e0a1e838f2d1f0ef2d83c7457f"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_linux_arm64.tar.gz"
      sha256 "d57a8884a5fff66b2fe2541a55443c74cd7321007f0798f875587c4e60422645"
    end
  end

  name "xmedia"
  desc "xmedia - Search and download movies & TV shows via your media server"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmedia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmedia"]
    end
  end

  # No zap stanza required

end
