# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmedia-server" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_darwin_amd64.tar.gz"
      sha256 "141f7680113d51499ea8c2f1ceff4712929760f21fa6030b410cdad6e97de8b1"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_darwin_arm64.tar.gz"
      sha256 "e6c37a1221c1a343d9699f17c28fe85569ffec568dba06c4464534b0715718be"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_linux_amd64.tar.gz"
      sha256 "71ff0dcf337f03d565046e1dc8fdc7d95d16694f60d1d0bb9046a4520764c081"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_linux_arm64.tar.gz"
      sha256 "c8c7e54bed0b8120d4d3fbd6b71da7e38def31026a5bd76ed6656fd112224e63"
    end
  end

  name "xmedia-server"
  desc "xmedia-server - Media stack API server for xmedia CLI"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmedia-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmedia-server"]
    end
  end

  # No zap stanza required

end
