# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmedia" do
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_darwin_amd64.tar.gz"
      sha256 "655fe7da08d1b16cd4ddeb6f01d1c92982e56051839f9162b572331cf8390074"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_darwin_arm64.tar.gz"
      sha256 "a5f54f028ec61f4a791fdb1211d1481305e9a534fee9f56d73f778a891620a01"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_linux_amd64.tar.gz"
      sha256 "22e90946f091f692deedfd575d58db0862cb04c7730d032694d615a7443e7b78"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_linux_arm64.tar.gz"
      sha256 "489890d02fe63de2a1cf1202277e0fb1aca426c4159a09e61672124176e89d9a"
    end
  end

  name "xmedia"
  desc "xmedia - Search and download movies & TV shows via your media server"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmedia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmedia"]
    end
  end

  # No zap stanza required

end
