# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmedia" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_darwin_amd64.tar.gz"
      sha256 "97600167485ee6890d28612b0c2e037c9f4c214ff9e89f83a5bede8b1ca2f7d6"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_darwin_arm64.tar.gz"
      sha256 "46d5f5dcc843e0cef50eca332e829c6f8bdeec7b2c2fb9cf2e49425325f81ad4"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_linux_amd64.tar.gz"
      sha256 "cb9405255186dfd152f5fe064196d65667d16dd105145b0d62a791f925575d49"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia/v#{version}/xmedia_#{version}_linux_arm64.tar.gz"
      sha256 "d7de24494f6c3cb4ea7a118e78b843abe1c27448cc229699843108b63af52379"
    end
  end

  name "xmedia"
  desc "xmedia - Search and download movies & TV shows via your media server"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmedia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmedia"]
    end
  end

  # No zap stanza required

end
