# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmedia-server" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_darwin_amd64.tar.gz"
      sha256 "4d5781922c48df86cd3a4b2cd4b051e8af56359ba2e77d89d7d651741c815be2"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_darwin_arm64.tar.gz"
      sha256 "4442f3820403d324bc4fde61a90a5f0f849c6d980fbe3684197ad96ed7ddbfb1"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_linux_amd64.tar.gz"
      sha256 "1bfece4c6234005b274d3a532c30b2a10ead86abdd435764719c28701e0a3c01"
    end
    on_arm do
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xmedia-server/v#{version}/xmedia-server_#{version}_linux_arm64.tar.gz"
      sha256 "54c661e6807a8c46cb6988af4b08b00baf7f40da56d5cff3ce518064efd130f0"
    end
  end

  name "xmedia-server"
  desc "xmedia-server - Media stack API server for xmedia CLI"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmedia-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmedia-server"]
    end
  end

  # No zap stanza required

end
