# This file was generated by GoReleaser. DO NOT EDIT.
cask "xpile" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bf42a785109edf6c1faa4771516e68a66a67f9d5430b377e7ac3a34ffae2f849"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xpile/v#{version}/xpile_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a442ba40d6bd8fdebeca5967c40e95b38c4bd5378b7001600df60bd0ccdce3e"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xpile/v#{version}/xpile_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10842afff6eaba03b1d3ed104fded5f0465439efd3538be02c08bc936bd2e812"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xpile/v#{version}/xpile_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a17eae60b6c49f200bab51de617bf29e750ea956935a397428009bc874848e4"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xpile/v#{version}/xpile_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xpile"
  desc "xpile - CLI client for the Unipile API (LinkedIn-first)"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xpile"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xpile"]
    end
  end

  # No zap stanza required

end
