# This file was generated by GoReleaser. DO NOT EDIT.
cask "xpolicy" do
  name "xpolicy"
  desc "xPolicy - Command-line interface for Azure Policy definitions"
  homepage "https://xtools.com/xpolicy"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xPolicy"

  on_macos do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_darwin_amd64.tar.gz"
      sha256 "44176fe1d61c02ef4015e329af41fccb0887cb6b5a35d36cead72c29864e99f4"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_darwin_arm64.tar.gz"
      sha256 "69e16609da0801dc2a955790c8e66e4b2b142a8a51873ce1bac04dc3a94ee708"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_linux_amd64.tar.gz"
      sha256 "531cbb5233f30f9427d3c13f0649a6ade86298fc2b5348565cc8f0a3fce35b78"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_linux_arm64.tar.gz"
      sha256 "06891e9725b76a524bf13f4255e710c30212a132ddfd4a6cf26f6b7fede026bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xpolicy"]
    end
  end

  # No zap stanza required
end
