# This file was generated by GoReleaser. DO NOT EDIT.
cask "xpolicy" do
  name "xpolicy"
  desc "xPolicy - Command-line interface for Azure Policy definitions"
  homepage "https://xtools.com/xpolicy"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xPolicy"

  on_macos do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_darwin_amd64.tar.gz"
      sha256 "d0674c55160897eb5e834a1d66013da1c1196f7440b851b717de09fb1a12683f"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_darwin_arm64.tar.gz"
      sha256 "3423a08394565850aed8c9e9c74f12f03c33202fdcbc7be01acc62a6698da204"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_linux_amd64.tar.gz"
      sha256 "8fec0c77e731377dcecb75008b9da45f74da3646f720515e1aabb2d9871e7b2e"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_linux_arm64.tar.gz"
      sha256 "054bf18ea00c5a28c65879ebc94f0c848e591083117644fb921f50f49ab815da"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xPolicy"]
    end
  end

  # No zap stanza required
end
