# This file was generated by GoReleaser. DO NOT EDIT.
cask "xpolicy" do
  name "xpolicy"
  desc "xPolicy - Command-line interface for Azure Policy definitions"
  homepage "https://xtools.com/xpolicy"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xPolicy"

  on_macos do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_darwin_amd64.tar.gz"
      sha256 "e56753b558c5103efc66c76cae556efdfb47b2838497346baca87eb2df52f1b6"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_darwin_arm64.tar.gz"
      sha256 "7d1204c757018baeadcc9e42dc5bd3662627eb7d6ad719165d256d41fc2186b9"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_linux_amd64.tar.gz"
      sha256 "92e00bcc9817a90ff7bd92f6e91089e67fff8d37abff63dea2ac4523bb10fa80"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xPolicy/v#{version}/xPolicy_#{version}_linux_arm64.tar.gz"
      sha256 "b221ffcdd9162ab6ce917eb5c51cb8806438032a6fbfa5f232d223efa48e3cdd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xpolicy"]
    end
  end

  # No zap stanza required
end
