# This file was generated by GoReleaser. DO NOT EDIT.
cask "xreview" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f049182249d99d6e231aa20eec96a8857f8c68b0103abc10eb8671c54bd03f6f"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "022723fbe633c600a7fc4c38637f6f490c769cf19799dfa6d51e3138cb437cd2"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9185a582075fa751fab1517274bb79e4fd6b05565d35c09b2102025461b7a33b"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "489197cfe355865f9f365dc56a5b1022c7d43647753f2ddef375a70438808e08"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xreview"
  desc "xreview - deterministic orchestrator for fresh, read-only AI code reviewers"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xreview"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xreview"]
    end
  end

  # No zap stanza required

end
