# This file was generated by GoReleaser. DO NOT EDIT.
cask "xreview" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ee164673555b9902ba006f0e00e62a5a86298d343cd9ad374fed7484baf500c1"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbdd6347c72c60de49c5b6bacc8c9ef7801c71644c3e772d29e6ef53b535b5e2"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3911144740fc3dca5559f31e25d0faf2a15b70b94e8bc7ab95f8ce04253bfb6c"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3ef13e53aaffcbe880feeee1cd92f69b5838e4f4c5d3cc2781f2ca096b65a93"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xreview"
  desc "xreview - deterministic orchestrator for fresh, read-only AI code reviewers"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xreview"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xreview"]
    end
  end

  # No zap stanza required

end
