# This file was generated by GoReleaser. DO NOT EDIT.
cask "xreview" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "78bc29d346d728ad41beb38f0e1d7c186dc6bb9763fe733b77f8a99823b57c50"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51e1b83d4eca3e0d23b6c663270184aa95bb067a49f0598a91886ce102d97a76"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ab46906eb878f531a8e50441ac29769e126aa02094a9432fce82514a43de944"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2fdd7e673841b8fdb27ffeb0b127c9daafb35249bd33ce2f378c2b5bce12df5"
      url "https://xtools-data.sfo3.digitaloceanspaces.com/downloads/xreview/v#{version}/xreview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "xreview"
  desc "xreview - deterministic orchestrator for fresh, read-only AI code reviewers"
  homepage "https://github.com/xtoolsio/xTools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xreview"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xreview"]
    end
  end

  # No zap stanza required

end
