# This file was generated by GoReleaser. DO NOT EDIT.
cask "xsign" do
  name "xsign"
  desc "xSign - Code signing and certificate management tool"
  homepage "https://github.com/xtoolsio/xTools"
  version "0.1.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xsign"

  on_macos do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Darwin_x86_64.tar.gz"
      sha256 "a76b7e4142ad7e8970c18eac620b4e695f2edb4594d38bbd497754e5ffece5b7"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Darwin_arm64.tar.gz"
      sha256 "33d167217a4f6200bbe79d099181072343eafecf2c585af165fb7f991202677e"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Linux_x86_64.tar.gz"
      sha256 "26bbe13c6fa9e8d6dd8e320af0791965ee59188acc45190b8824ad63c6dfaa61"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Linux_arm64.tar.gz"
      sha256 "220be61d9dd4572f8be80ef9f7e2f2e57bd01870a8112ad0b5ee4d1762baed52"
    end
  end

  # No zap stanza required
end
