# This file was generated by GoReleaser. DO NOT EDIT.
cask "xsign" do
  name "xsign"
  desc "xSign - Code signing and certificate management tool"
  homepage "https://github.com/xtoolsio/xTools"
  version "0.1.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xsign"

  on_macos do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Darwin_x86_64.tar.gz"
      sha256 "8debc2cb353a1e01f31a6f487dd7613dd6200b086a06fb3c61940823909cde60"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Darwin_arm64.tar.gz"
      sha256 "081ff369078bd80dae16e5ff2f61990d8e0f861da579225ae0acb026844b800a"
    end
  end

  on_linux do
    on_intel do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Linux_x86_64.tar.gz"
      sha256 "4ebe6b37a216e3ac6a04807390dbc2065c76a9f9df47b3613fb11d00a4ec5069"
    end
    on_arm do
      url "https://xtools.blob.core.windows.net/downloads/xSign/v#{version}/xsign_Linux_arm64.tar.gz"
      sha256 "fa7ef6908236b27b6e8a96cd964b1daf9ebe520c9fa0caf1be9e61f8ea389ce7"
    end
  end

  # No zap stanza required
end
