# This file was generated by GoReleaser. DO NOT EDIT.
cask "xsign" do
  name "xsign"
  desc "xSign - Code signing and certificate management tool"
  homepage "https://github.com/xtoolsio/xTools"
  version "0.1.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xsign"

  on_macos do
    on_intel do
      url "https://github.com/xtoolsio/xTools/releases/download/v#{version}/xsign_Darwin_x86_64.tar.gz"
      sha256 "9c4669d87b24019560fdb1b8ec5f3d238e0bf3b6150f2dcbfef6c8f5057ba820"
    end
    on_arm do
      url "https://github.com/xtoolsio/xTools/releases/download/v#{version}/xsign_Darwin_arm64.tar.gz"
      sha256 "d345be9bd8c1f13f51764109d5625b9b63baed0cffa862de84aef484c967db28"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xtoolsio/xTools/releases/download/v#{version}/xsign_Linux_x86_64.tar.gz"
      sha256 "9d5d3f26911927d0cc4a4f6359d35163622c315966e4f125a6f3c7ff3764e8a4"
    end
    on_arm do
      url "https://github.com/xtoolsio/xTools/releases/download/v#{version}/xsign_Linux_arm64.tar.gz"
      sha256 "392566a3ab3fc3ecb8d58f188ae061f23724feebb907cfac746d657a9d5ead97"
    end
  end

  # No zap stanza required
end
